# Generated by Django 3.1.7 on 2021-06-09 18:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Origines',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('aprendiz', 'Aprendiz'), ('instructor', 'Instructor')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de componente',
                'verbose_name_plural': 'Tipos de componentes',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='samples')),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.component')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.origin')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.person')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.type'),
        ),
    ]
