# Generated by Django 3.1.7 on 2021-04-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons')),
                ('rol', models.CharField(choices=[('aprendiz', 'Aprendiz'), ('instructor', 'Instructor')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('demolition_method', models.CharField(choices=[('mecanica', 'Mecanica'), ('manual', 'Manual')], max_length=50)),
                ('origin', models.CharField(choices=[('columna', 'Columna'), ('losa', 'Losa'), ('viga', 'Viga')], max_length=50)),
                ('demolition_object', models.CharField(choices=[('mejora', 'Mejora'), ('estructural', 'Estructural')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='samples')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.person')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.type')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
    ]
