# Generated by Django 3.1.7 on 2021-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='123@123.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
