# Generated by Django 3.1.7 on 2021-08-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('registrado', 'Registrado'), ('administrador', 'Administrador')], default='registrado', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Residuo', 'verbose_name_plural': 'Residuos'},
        ),
        migrations.AddField(
            model_name='sample',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.area')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.program')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.rol'),
        ),
    ]
