# Generated by Django 3.1.7 on 2021-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210818_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
