# Generated by Django 3.1.7 on 2021-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210823_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
